name: ci workflow
on: push

jobs:
  test-job:
    name: check the role
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: check versions
      run: |
        python3 --version
        pip3 --version
        ansible --version

    - name: prepare tests
      run: |
        pip3 install -r requirements.txt
        printf '[defaults]\nroles_path=../' >ansible.cfg
        touch -- "-a b.sh"
        chmod +x -- "-a b.sh"

    - name: syntax check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    - name: run ci check
      run: ansible-playbook tests/test.yml -i tests/inventory

  deploy-job:
    runs-on: ubuntu-20.04
    needs: [ test-job ]
    if: github.ref_type	== 'tag' && github.ref_protected == true
    run: echo this is deploy job
