name: ci workflow
on: push

jobs:
  test-job:
    name: test the role
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3

    - name: check versions
      run: |
        python3 --version
        pip3 --version
        ansible --version

    - name: prepare tests
      run: |
        pip3 install -r requirements.txt
        printf '[defaults]\nroles_path=../' >ansible.cfg
        touch -- "-a b.sh"
        chmod +x -- "-a b.sh"

    - name: syntax check
      run: ansible-playbook tests/test.yml -i tests/inventory --syntax-check

    - name: run ci check
      run: ansible-playbook tests/test.yml -i tests/inventory

  lint-job:
    name: lint codes
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - uses: ansible/ansible-lint-action@main

  deploy-job:
    name: deploy the role on tag
    runs-on: ubuntu-20.04
    needs: [ test-job, lint-job ]
    if: github.ref_type == 'tag'
    steps:
    - uses: actions/checkout@v3
    - name: publish the role to Galaxy
      uses: robertdebock/galaxy-action@1.2.1
      with:
        galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
        git_branch: ${{ github.ref_name }}
